-- Database: paleohumans

-- DROP DATABASE IF EXISTS paleohumans;

CREATE DATABASE paleohumans
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE site (
    site_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name TEXT NOT NULL UNIQUE,
    country TEXT NOT NULL,
    region TEXT NOT NULL,
    municipality TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    description TEXT,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE culture_phase_enum AS ENUM ('EARLY_UPPER_PALAEOLITHIC', 'FULL_UPPER_PALAEOLITHIC', 'FINAL_UPPER_PALAEOLITHIC', 'UNCERTAIN');

CREATE TABLE culture (
    culture_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    culture_name TEXT NOT NULL UNIQUE,
    phase        culture_phase_enum NOT NULL,
    start_bp     INTEGER NOT NULL,
    end_bp       INTEGER NOT NULL,
    color        TEXT NOT NULL,
    color_rgb    TEXT NOT NULL,
    region       TEXT,
    description  TEXT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_culture_bp_range CHECK (start_bp >= end_bp)
);

CREATE TABLE culture_feature (
    culture_feature_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    culture_id          INTEGER NOT NULL REFERENCES culture(culture_id) ON DELETE CASCADE,
    feature             TEXT    NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE archaeological_context (
    archaeological_context_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id INTEGER NOT NULL REFERENCES site(site_id) ON DELETE CASCADE,
    stratigraphic_context TEXT NOT NULL,
    culture_id INTEGER REFERENCES culture(culture_id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE sex_enum AS ENUM ('MALE', 'FEMALE', 'INDETERMINATE');
CREATE TYPE age_class_main_enum AS ENUM ('SUBADULT', 'ADULT', 'INDETERMINATE', 'SUBADULT_ADULT');
CREATE TYPE age_class_subcategory_enum AS ENUM ('PERINATAL', 'FETAL', 'INFANT_I', 'INFANT_II', 'JUVENILE', 'YOUNG_ADULT', 'SENILE_ADULT', 'MATURE_ADULT');
CREATE TYPE age_unit_enum AS ENUM ('MONTHS', 'YEARS');
CREATE TYPE individual_type_enum AS ENUM ('INDIVIDUAL', 'MIXED_INDIVIDUALS', 'UNASSIGNED_REMAINS');

CREATE TABLE individual (
    individual_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archaeological_context_id INTEGER NOT NULL REFERENCES archaeological_context(archaeological_context_id) ON DELETE CASCADE,
    individual_name TEXT,
    individual_type individual_type_enum NOT NULL,
    mni TEXT NOT NULL DEFAULT '1',
    mni_statistical INTEGER GENERATED ALWAYS AS (
      CASE
        WHEN mni ~ '^[1-9][0-9]*$' THEN mni::INTEGER
        WHEN mni = '?' THEN 1
        ELSE 1
      END
    ) STORED,
    CONSTRAINT chk_mni_format CHECK (mni = '?' OR mni ~ '^[1-9][0-9]*$'),
    age_at_death_text TEXT,
    age_at_death_min INTEGER,
    age_at_death_max INTEGER,
    age_unit age_unit_enum,
    age_class_main age_class_main_enum NOT NULL,
    age_class_subcategory age_class_subcategory_enum,
    sex sex_enum NOT NULL,
    sex_certain BOOLEAN NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_age_range CHECK (age_at_death_min IS NULL OR age_at_death_max IS NULL OR age_at_death_min <= age_at_death_max),
    CONSTRAINT chk_individual_type_mni_consistency CHECK (
      (individual_type = 'INDIVIDUAL' AND mni = '1')
      OR
      (individual_type IN ('MIXED_INDIVIDUALS') AND mni <> '1')
      OR
      (individual_type = 'UNASSIGNED_REMAINS')
    )
);

CREATE TYPE bone_category_enum AS ENUM ('TOOTH', 'VERTEBRA', 'RIB', 'PHALANX', 'OTHER');
CREATE TYPE skeleton_main_enum AS ENUM ('CRANIAL', 'POSTCRANIAL');
CREATE TYPE skeleton_region_enum AS ENUM ('NEUROCRANIUM', 'SPLANCHNOCRANIUM', 'UPPER_LIMB', 'LOWER_LIMB', 'HANDS', 'FEET', 'PELVIS', 'TORSO');
CREATE TYPE bone_term_type_enum AS ENUM ('ATOMIC', 'GROUPED', 'VAGUE_STRUCTURED', 'VAGUE_GENERIC');

CREATE TABLE bone_catalog (
  bone_catalog_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bone_catalog_name TEXT NOT NULL UNIQUE,
  skeleton_main skeleton_main_enum,
  skeleton_region skeleton_region_enum,
  bone_category bone_category_enum NOT NULL,
  term_type bone_term_type_enum NOT NULL DEFAULT 'ATOMIC',
  parent_bone_catalog_id INTEGER REFERENCES bone_catalog(bone_catalog_id) ON DELETE SET NULL
);

CREATE TYPE tooth_type_enum AS ENUM ('DECIDUOUS', 'PERMANENT', 'SUPERNUMERARY', 'UNKNOWN');
CREATE TYPE laterality_enum AS ENUM ('LEFT', 'RIGHT', 'UNKNOWN');
CREATE TYPE phalanx_type_enum AS ENUM ('HAND', 'FOOT');
CREATE TYPE vertebra_type_enum AS ENUM ('CERVICAL', 'THORACIC', 'LUMBAR', 'UNKNOWN');
CREATE TYPE tooth_vertical_position_enum AS ENUM ('UPPER', 'LOWER', 'UNKNOWN');
CREATE TYPE hand_foot_bone_segment_enum AS ENUM ('PROXIMAL', 'MIDDLE', 'DISTAL', 'INTERMEDIATE', 'LATERAL', 'UNKNOWN');

CREATE TABLE bone (
    bone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    individual_id INTEGER NOT NULL REFERENCES individual(individual_id) ON DELETE CASCADE,
    bone_catalog_id INTEGER NOT NULL REFERENCES bone_catalog(bone_catalog_id) ON DELETE RESTRICT,
    bone_source TEXT NOT NULL,
    specimen_name TEXT,
    repository TEXT,
    year_discovery TEXT,
    bone_processing BOOLEAN,
    bone_quantity_source TEXT,
    bone_quantity_min INTEGER NOT NULL,
    laterality laterality_enum,
    tooth_type tooth_type_enum,
    tooth_vertical_position tooth_vertical_position_enum,
    tooth_number INTEGER,
    tooth_number_confidence BOOLEAN,
    vertebra_type vertebra_type_enum,
    vertebra_number INTEGER,
    vertebra_number_confidence BOOLEAN,
    phalanx_type phalanx_type_enum,
    phalanx_number INTEGER,
    phalanx_number_confidence BOOLEAN,
    hand_foot_bone_segment hand_foot_bone_segment_enum,
    rib_number INTEGER,
    rib_number_confidence BOOLEAN,
    bone_details TEXT,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_bone_quantity_min_positive CHECK (bone_quantity_min >= 1)
);

-- Anatomical decomposition of grouped terms in bone_catalog.
-- Defined as a view because the composition of the human skeleton is a
-- fixed anatomical fact, not observational data. Keeping it in code
-- prevents accidental edits and keeps the domain knowledge versioned
-- alongside the schema.
--
-- Columns:
--   bone_catalog_id           -> the grouped term (e.g. coxal, neurocranium)
--   component_bone_catalog_id -> the atomic term it contains (e.g. ilium)
--   component_quantity        -> how many of that component the grouped term contains
--
-- Usage is identical to the previous table: JOIN bone_catalog_component
-- ON bone.bone_catalog_id = bone_catalog_component.bone_catalog_id
CREATE OR REPLACE VIEW bone_catalog_component
  (bone_catalog_id, component_bone_catalog_id, component_quantity) AS
VALUES
  -- cranium (62) -> neurocranium + splanchnocranium
  (62, 63, 1::numeric),
  (62, 64, 1::numeric),
  -- neurocranium (63) -> frontal, occipital, parietal x2, sphenoid, temporal x2, ethmoid
  (63,  1, 1::numeric),
  (63,  2, 1::numeric),
  (63,  3, 2::numeric),
  (63,  4, 1::numeric),
  (63,  5, 2::numeric),
  (63, 11, 1::numeric),
  -- splanchnocranium (64) -> mandible, maxilla x2, palatine x2, zygomatic x2,
  --                          nasal x2, lacrimal x2, vomer, inferior nasal concha x2
  (64,  9, 1::numeric),
  (64, 10, 2::numeric),
  (64, 13, 2::numeric),
  (64, 16, 2::numeric),
  (64, 55, 2::numeric),
  (64, 56, 2::numeric),
  (64, 57, 1::numeric),
  (64, 58, 2::numeric),
  -- coxal (65) -> ilium, ischium, pubis
  (65, 42, 1::numeric),
  (65, 43, 1::numeric),
  (65, 44, 1::numeric);

CREATE TYPE skeleton_category_enum AS ENUM ('ALMOST_COMPLETE_SKELETON', 'COMPLETE_SKELETON', 'PARTIAL_SKELETON', 'INCOMPLETE_SKELETON', 'POSTCRANIAL_SKELETON', 'UNDEFINED_SKELETON');

CREATE TABLE skeleton (
  skeleton_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_id INTEGER NOT NULL REFERENCES individual(individual_id) ON DELETE CASCADE,
  skeleton_category skeleton_category_enum NOT NULL,
  preservation_index NUMERIC CHECK (preservation_index >= 0 AND preservation_index <= 100),
  specimen_name TEXT,
  repository TEXT,
  year_discovery TEXT,
  bone_processing BOOLEAN,
  description TEXT,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE dating_technique (
  dating_technique_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dating_technique_name TEXT NOT NULL UNIQUE,
  description TEXT,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE dating_type_enum AS ENUM ('DIRECT', 'INDIRECT', 'UNCERTAIN');
CREATE TYPE sample_origin_enum AS ENUM ('CONTEXT', 'BONE', 'SKELETON');

CREATE TABLE dated_sample (
    dated_sample_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_origin sample_origin_enum NOT NULL,
    archaeological_context_id INTEGER NULL REFERENCES archaeological_context(archaeological_context_id),
    bone_id INTEGER NULL REFERENCES bone(bone_id),
    skeleton_id INTEGER NULL REFERENCES skeleton(skeleton_id),
    material TEXT NOT NULL,
    dating_type dating_type_enum NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CHECK (
      (CASE WHEN archaeological_context_id IS NOT NULL THEN 1 ELSE 0 END +
       CASE WHEN bone_id IS NOT NULL THEN 1 ELSE 0 END +
       CASE WHEN skeleton_id IS NOT NULL THEN 1 ELSE 0 END) = 1
    ),

    CHECK (
      (sample_origin = 'CONTEXT' AND archaeological_context_id IS NOT NULL)
      OR
      (sample_origin = 'BONE' AND bone_id IS NOT NULL)
      OR
      (sample_origin = 'SKELETON' AND skeleton_id IS NOT NULL)
    ),

    CONSTRAINT chk_dating_type_origin_consistency CHECK (
      (sample_origin = 'CONTEXT' AND dating_type IN ('INDIRECT', 'UNCERTAIN'))
      OR
      (sample_origin IN ('BONE', 'SKELETON') AND dating_type IN ('DIRECT', 'UNCERTAIN'))
    )
);

CREATE TABLE dating_result (
	dating_result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    	dated_sample_id INTEGER NOT NULL REFERENCES dated_sample(dated_sample_id) ON DELETE CASCADE,
        dating_technique_id INTEGER NOT NULL REFERENCES dating_technique(dating_technique_id) ON DELETE RESTRICT,
	dates_bp_uncal NUMERIC,
	dates_range NUMERIC,
	notes TEXT,
        updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE bibliographic_reference (
  bibliographic_reference_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  authors TEXT NOT NULL,
  year INTEGER NOT NULL,
  title TEXT NOT NULL,
  journal TEXT NOT NULL,
  volume TEXT,
  issue TEXT,
  pages TEXT,
  doi TEXT,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE site_bibliographic_reference (
  site_id INTEGER NOT NULL REFERENCES site(site_id) ON DELETE CASCADE,
  bibliographic_reference_id INTEGER NOT NULL REFERENCES bibliographic_reference(bibliographic_reference_id) ON DELETE CASCADE,
  PRIMARY KEY (site_id, bibliographic_reference_id)
);

CREATE TABLE archaeological_context_bibliographic_reference (
  archaeological_context_id INTEGER NOT NULL REFERENCES archaeological_context(archaeological_context_id) ON DELETE CASCADE,
  bibliographic_reference_id INTEGER NOT NULL REFERENCES bibliographic_reference(bibliographic_reference_id) ON DELETE CASCADE,
  PRIMARY KEY (archaeological_context_id, bibliographic_reference_id)
);

CREATE TYPE burial_context_enum AS ENUM ('YES', 'NO', 'POSSIBLE', 'UNCERTAIN');
CREATE TYPE burial_type_enum AS ENUM ('PRIMARY_SINGLE_BURIAL', 'PRIMARY_DOUBLE_BURIAL', 'PRIMARY_TRIPLE_BURIAL', 'PRIMARY_MULTIPLE_BURIAL', 'SECONDARY_SINGLE_BURIAL', 'SECONDARY_DOUBLE_BURIAL', 'SECONDARY_TRIPLE_BURIAL', 'SECONDARY_MULTIPLE_BURIAL');

CREATE TABLE funerary_context (
  funerary_context_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archaeological_context_id INTEGER NOT NULL REFERENCES archaeological_context(archaeological_context_id) ON DELETE CASCADE,
  burial_context burial_context_enum NOT NULL DEFAULT 'UNCERTAIN',
  burial_type burial_type_enum,
  ochre_presence BOOLEAN,
  grave_goods BOOLEAN,
  notes TEXT,
  updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_funerary_context_type CHECK (
      (burial_context = 'NO' AND burial_type IS NULL)
      OR
      (burial_context = 'YES' AND burial_type IS NOT NULL)
      OR
      (burial_context IN ('POSSIBLE', 'UNCERTAIN'))
    )
);

CREATE TABLE funerary_context_individual (
  funerary_context_id INTEGER NOT NULL REFERENCES funerary_context(funerary_context_id) ON DELETE CASCADE,
  individual_id INTEGER NOT NULL REFERENCES individual(individual_id) ON DELETE CASCADE,
  PRIMARY KEY (funerary_context_id, individual_id)
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_site_updated_at ON site;
CREATE TRIGGER trg_site_updated_at
BEFORE INSERT OR UPDATE ON site
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_archaeological_context_updated_at ON archaeological_context;
CREATE TRIGGER trg_archaeological_context_updated_at
BEFORE INSERT OR UPDATE ON archaeological_context
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_individual_updated_at ON individual;
CREATE TRIGGER trg_individual_updated_at
BEFORE INSERT OR UPDATE ON individual
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_bone_updated_at ON bone;
CREATE TRIGGER trg_bone_updated_at
BEFORE INSERT OR UPDATE ON bone
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_bibliographic_reference_updated_at ON bibliographic_reference;
CREATE TRIGGER trg_bibliographic_reference_updated_at
BEFORE INSERT OR UPDATE ON bibliographic_reference
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_skeleton_updated_at ON skeleton;
CREATE TRIGGER trg_skeleton_updated_at
BEFORE INSERT OR UPDATE ON skeleton
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_culture_updated_at ON culture;
CREATE TRIGGER trg_culture_updated_at
BEFORE INSERT OR UPDATE ON culture
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_culture_feature_updated_at ON culture_feature;
CREATE TRIGGER trg_culture_feature_updated_at
BEFORE INSERT OR UPDATE ON culture_feature
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_dating_technique_updated_at ON dating_technique;
CREATE TRIGGER trg_dating_technique_updated_at
BEFORE INSERT OR UPDATE ON dating_technique
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_dated_sample_updated_at ON dated_sample;
CREATE TRIGGER trg_dated_sample_updated_at
BEFORE INSERT OR UPDATE ON dated_sample
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_dating_result_updated_at ON dating_result;
CREATE TRIGGER trg_dating_result_updated_at
BEFORE INSERT OR UPDATE ON dating_result
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_funerary_context_updated_at ON funerary_context;
CREATE TRIGGER trg_funerary_context_updated_at
BEFORE INSERT OR UPDATE ON funerary_context
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE app_user (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_token (
  token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  token_hash VARCHAR(255) NOT NULL UNIQUE,
  family_id VARCHAR(64) NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  family_expires_at TIMESTAMPTZ NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at TIMESTAMPTZ NULL,
  replaced_by_token_id BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user(user_id),
  CONSTRAINT fk_refresh_token_replaced_by FOREIGN KEY (replaced_by_token_id) REFERENCES refresh_token(token_id)
);

CREATE INDEX idx_refresh_token_user_id ON refresh_token(user_id);
CREATE INDEX idx_refresh_token_expires_at ON refresh_token(expires_at);
CREATE INDEX idx_refresh_token_family_id ON refresh_token(family_id);
CREATE INDEX idx_archaeological_context_site_id ON archaeological_context(site_id);
CREATE INDEX idx_archaeological_context_culture_id ON archaeological_context(culture_id);
CREATE INDEX idx_individual_archaeological_context_id ON individual(archaeological_context_id);
CREATE INDEX idx_individual_sex ON individual(sex);
CREATE INDEX idx_individual_age_class_main ON individual(age_class_main);
CREATE INDEX idx_bone_individual_id ON bone(individual_id);
CREATE INDEX idx_bone_bone_catalog_id ON bone(bone_catalog_id);
CREATE INDEX idx_skeleton_individual_id ON skeleton(individual_id);
CREATE INDEX idx_dated_sample_context_id ON dated_sample(archaeological_context_id);
CREATE INDEX idx_dated_sample_bone_id ON dated_sample(bone_id);
CREATE INDEX idx_dated_sample_skeleton_id ON dated_sample(skeleton_id);
CREATE INDEX idx_dating_result_sample_id ON dating_result(dated_sample_id);
CREATE INDEX idx_dating_result_technique_id ON dating_result(dating_technique_id);
CREATE INDEX idx_funerary_context_archaeological_context_id ON funerary_context(archaeological_context_id);
CREATE INDEX idx_funerary_context_individual_individual_id ON funerary_context_individual(individual_id);